"""initial recovery schema

Revision ID: b818e8fa6630
Revises: 
Create Date: 2026-09-05 09:54:47.877116
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=96), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_mission_id'), ['mission_id'], unique=False)

    op.create_table('constraint_evaluations',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('constraint_id', sa.String(length=64), nullable=False),
    sa.Column('constraint_key', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('required_value', sa.JSON(), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraint_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraint_evaluations_constraint_id'), ['constraint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constraint_evaluations_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_constraint_evaluations_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('operational_exceptions',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('entity_ref', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threatened_outcome', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_decisions',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('rule', sa.String(length=96), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_decisions_mission_id'), ['mission_id'], unique=False)

    op.create_table('recovery_decisions',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('constraint_ids', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_decisions_mission_id'), ['mission_id'], unique=False)

    op.create_table('recovery_outcomes',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('selected_strategy_id', sa.String(length=64), nullable=True),
    sa.Column('selected_target', sa.String(length=128), nullable=True),
    sa.Column('protected_outcome', sa.Text(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('margin_seconds', sa.Integer(), nullable=True),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_outcomes_mission_id'), ['mission_id'], unique=True)

    op.create_table('replans',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=48), nullable=False),
    sa.Column('previous_strategy_id', sa.String(length=64), nullable=False),
    sa.Column('new_strategy_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_evidence_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_call_id', sa.String(length=128), nullable=True),
    sa.Column('violated_constraint_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('required_value', sa.JSON(), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replans_mission_id'), ['mission_id'], unique=False)

    op.create_table('recovery_missions',
    sa.Column('exception_id', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('recovery_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_strategy_id', sa.String(length=64), nullable=True),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('authority', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['operational_exceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_missions_exception_id'), ['exception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_missions_status'), ['status'], unique=False)

    op.create_table('evidence',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extractor', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('information_needs',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_for', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('information_needs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_information_needs_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_needs_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('mission_constraints',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('required_value', sa.JSON(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'key', name='uq_constraint_mission_key')
    )
    with op.batch_alter_table('mission_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_constraints_mission_id'), ['mission_id'], unique=False)

    op.create_table('mission_events',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('constraint_id', sa.String(length=64), nullable=True),
    sa.Column('replan_id', sa.String(length=64), nullable=True),
    sa.Column('strategic', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'sequence', name='uq_event_mission_sequence')
    )
    with op.batch_alter_table('mission_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_events_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index('ix_mission_events_mission_seq', ['mission_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_events_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_events_type'), ['type'], unique=False)

    op.create_table('phone_operations',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('target_phone', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=48), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('requested_facts', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('result_schema', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('triggered_by_evidence_id', sa.String(length=64), nullable=True),
    sa.Column('triggered_by_replan_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_operations_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_operations_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_operations_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('recovery_candidates',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('attempted', sa.Boolean(), nullable=False),
    sa.Column('exhausted', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_candidates_mission_id'), ['mission_id'], unique=False)

    op.create_table('recovery_strategies',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('target_candidate_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('information_needed', sa.JSON(), nullable=False),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_strategies_mission_id'), ['mission_id'], unique=False)

    op.create_table('call_records',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_mode', sa.String(length=16), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('display_ref', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('structured_result', sa.JSON(), nullable=False),
    sa.Column('result_validation', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('transcript_excerpt', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['phone_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_call_id'), ['call_id'], unique=False)
        batch_op.create_index('ix_call_records_call_id_unique', ['call_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_call_records_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_operation_id'), ['operation_id'], unique=False)

    op.create_table('recovery_attempts',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['recovery_missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['recovery_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_attempts_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_attempts_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_attempts_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_attempts_mission_id'))

    op.drop_table('recovery_attempts')
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_operation_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_mission_id'))
        batch_op.drop_index('ix_call_records_call_id_unique')
        batch_op.drop_index(batch_op.f('ix_call_records_call_id'))

    op.drop_table('call_records')
    with op.batch_alter_table('recovery_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_strategies_mission_id'))

    op.drop_table('recovery_strategies')
    with op.batch_alter_table('recovery_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_candidates_mission_id'))

    op.drop_table('recovery_candidates')
    with op.batch_alter_table('phone_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_operations_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_phone_operations_mission_id'))
        batch_op.drop_index(batch_op.f('ix_phone_operations_attempt_id'))

    op.drop_table('phone_operations')
    with op.batch_alter_table('mission_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_events_type'))
        batch_op.drop_index(batch_op.f('ix_mission_events_sequence'))
        batch_op.drop_index('ix_mission_events_mission_seq')
        batch_op.drop_index(batch_op.f('ix_mission_events_mission_id'))

    op.drop_table('mission_events')
    with op.batch_alter_table('mission_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_constraints_mission_id'))

    op.drop_table('mission_constraints')
    with op.batch_alter_table('information_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_information_needs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_information_needs_mission_id'))

    op.drop_table('information_needs')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_operation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_mission_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_call_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('recovery_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_missions_status'))
        batch_op.drop_index(batch_op.f('ix_recovery_missions_exception_id'))

    op.drop_table('recovery_missions')
    with op.batch_alter_table('replans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replans_mission_id'))

    op.drop_table('replans')
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_outcomes_mission_id'))

    op.drop_table('recovery_outcomes')
    with op.batch_alter_table('recovery_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_decisions_mission_id'))

    op.drop_table('recovery_decisions')
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_decisions_mission_id'))

    op.drop_table('policy_decisions')
    op.drop_table('operational_exceptions')
    with op.batch_alter_table('constraint_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraint_evaluations_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_constraint_evaluations_mission_id'))
        batch_op.drop_index(batch_op.f('ix_constraint_evaluations_constraint_id'))

    op.drop_table('constraint_evaluations')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_mission_id'))

    op.drop_table('approval_requests')
    # ### end Alembic commands ###
