"""THE test.

Same mission, same code path, same candidates - only what the carrier says on
the phone differs. If the second call appeared regardless, PHONEOPS would be a
scripted demo. It does not.

    Carrier B says 16:00 -> constraint satisfied -> Carrier B kept, NO Carrier C call
    Carrier B says 18:00 -> cutoff violated -> strategy invalidated -> Carrier C called
"""

from __future__ import annotations

import pytest

from app.domain.enums import (
    ConstraintStatus,
    MissionStatus,
    OutcomeStatus,
    StrategyStatus,
)
from app.engine import director
from app.services.mission_service import create_exception_and_mission, get_mission
from app.services.view import build_recovery_view
from tests.conftest import flagship_payload

BASE_SCRIPT = {"available": True, "capacity_ok": True, "confirmed": True}


async def _run(session, pickup_time: str):
    payload = flagship_payload(carrier_b_script={**BASE_SCRIPT, "pickup_time": pickup_time})
    mission = await create_exception_and_mission(session, payload)
    await director.start_mission(session, mission.id)
    mission = await get_mission(session, mission.id)
    return await build_recovery_view(session, mission)


@pytest.mark.asyncio
async def test_case_a_evidence_within_cutoff_keeps_the_first_strategy(session, calle):
    view = await _run(session, "16:00")

    targets = [op.target for op in view.operations]
    assert targets == ["Carrier B"], "no second call may exist when the first path is viable"
    assert view.mission.replan_count == 0
    assert view.latest_replan is None

    strategies = {s.target: s.status for s in view.strategies}
    assert strategies == {"Carrier B": StrategyStatus.SUCCESSFUL}
    assert "Carrier C" not in strategies

    assert view.mission.status == MissionStatus.RECOVERED
    assert view.outcome is not None
    assert view.outcome.selected_target == "Carrier B"
    assert view.outcome.status == OutcomeStatus.RECOVERED


@pytest.mark.asyncio
async def test_case_b_evidence_past_cutoff_forces_a_replan_and_a_second_call(session, calle):
    view = await _run(session, "18:00")

    targets = [op.target for op in view.operations]
    assert targets == ["Carrier B", "Carrier C"]
    assert view.mission.replan_count == 1

    strategies = {s.target: s.status for s in view.strategies}
    assert strategies["Carrier B"] == StrategyStatus.INVALIDATED
    assert strategies["Carrier C"] == StrategyStatus.SUCCESSFUL

    assert view.mission.status == MissionStatus.RECOVERED
    assert view.outcome.selected_target == "Carrier C"
    assert view.outcome.facts["pickup_time"] == "16:45"


@pytest.mark.asyncio
async def test_the_second_call_is_causally_linked_to_the_first(session, calle):
    """Not just 'a second call happened' - it must point back to the evidence."""
    view = await _run(session, "18:00")

    second = view.operations[1]
    replan = view.latest_replan
    assert replan is not None

    # The second operation was generated by the replan...
    assert second.triggered_by_replan_id == replan.id
    # ...which was triggered by evidence obtained on the first call...
    assert second.triggered_by_evidence_id == replan.trigger_evidence_id

    first_call_id = view.operations[0].calls[0].call_id
    assert replan.trigger_call_id == first_call_id

    # ...and that evidence is the 18:00 pickup time from Carrier B.
    trigger = next(e for e in view.evidence if e.id == replan.trigger_evidence_id)
    assert trigger.subject == "Carrier B"
    assert trigger.type == "pickup_time"
    assert trigger.value["value"] == "18:00"
    assert trigger.call_id == first_call_id

    assert replan.required_value["value"] == "17:30"
    assert replan.observed_value["value"] == "18:00"


@pytest.mark.asyncio
async def test_only_the_deadline_constraint_differs_between_the_two_cases(session, calle):
    """Both runs evaluate the same constraints; only the verdict changes."""
    viable = await _run(session, "16:00")
    b_evals = [e for e in viable.constraint_evaluations if e.subject == "Carrier B"]
    assert {e.status for e in b_evals} == {ConstraintStatus.SATISFIED}


@pytest.mark.asyncio
async def test_carrier_b_evidence_never_validates_a_carrier_c_strategy(session, calle):
    """Evidence is scoped by subject - no cross-contamination between targets."""
    view = await _run(session, "18:00")

    for evaluation in view.constraint_evaluations:
        for evidence_id in evaluation.evidence_ids:
            evidence = next(e for e in view.evidence if e.id == evidence_id)
            assert evidence.subject == evaluation.subject
